#!/bin/sh
PRODUCT_NAME="`cat /sys/class/dmi/id/product_name`"

[ -z "$PRODUCT_NAME" ] && PRODUCT_NAME="DA-820C"

if [ "$1" = "-a" ]; then
	str_version="$PRODUCT_NAME firmware version `cat /etc/.moxaversion` Build `cat /etc/.moxabuildtime`"
else
	str_version="$PRODUCT_NAME"
fi

echo $str_version
