#! /bin/bash

ft260_bind() {
	for filename in /sys/bus/i2c/devices/i2c-*/name; do
		i2c_devname=$(cat ${filename})
		if [[ $i2c_devname == *"FT260"* ]]; then
			i2c_devpath=$(echo ${filename%/*})
			echo "pca9535 0x26" > ${i2c_devpath}/new_device
			echo "pca9535 0x27" > ${i2c_devpath}/new_device
		fi
	done
}

case "$1" in
	start)
		ft260_bind
	;;
	*)
		echo "Usage: $0 start" >&2
		exit 3
	;;
esac
